services:
  ### ===================================
  ### API SERVICE TERITORY
  ### ===================================
  api:
    container_name: go-api
    image: go-fast-search:latest
    restart: always
    command: ./api
    healthcheck:
      interval: 120ms
      start_period: 60ms
      timeout: 30ms
      retries: 3
      test: env | grep $HOME
    env_file:
      - .env
    depends_on:
      - db
      - cache
    ports:
      - 3000:3000
    networks:
       - go-network
  ### ===================================
  ### WORKER SERVICE TERITORY
  ### ===================================
  worker:
    container_name: go-worker
    image: go-fast-search:latest
    restart: always
    command: ./worker
    healthcheck:
      interval: 120ms
      start_period: 60ms
      timeout: 30ms
      retries: 3
      test: env | grep $HOME
    env_file:
      - .env
    depends_on:
      - db
      - cache
    expose:
      - 3000
    networks:
       - go-network
  ### ===================================
  ### DATABASE SERVICE TERITORY
  ### ===================================
  db:
    image: postgres:14-alpine
    restart: always
    healthcheck:
      interval: 120ms
      start_period: 60ms
      timeout: 30ms
      retries: 3
      test: env | grep $HOME
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
       - go-network
  ### ===================================
  ### CACHING SERVICE TERITORY
  ### ===================================
  cache:
    image: redis:7-alpine
    restart: always
    healthcheck:
      interval: 120ms
      start_period: 60ms
      timeout: 30ms
      retries: 3
      test: env | grep $HOME
    ports:
      - 6379:6379
    networks:
       - go-network
  ### ===================================
  ### SEARCH SERVICE TERITORY
  ### ===================================
  search:
    image: getmeili/meilisearch:latest
    restart: always
    healthcheck:
      interval: 120ms
      start_period: 60ms
      timeout: 30ms
      retries: 3
      test: env | grep $HOME
    env_file:
      - .env
    ports:
      - 7700:7700
    networks:
       - go-network
  ### ===================================
  ### NETWORKS SHARING GROUP TERITORY
  ### ===================================
networks:
  go-network: