services:
  ### ===================================
  ### API SERVICE TERITORY
  ### ===================================
  web:
    container_name: web
    image: web:latest
    restart: always
    mem_limit: 512m
    mem_swappiness: 70
    healthcheck:
      interval: 120ms
      start_period: 60ms
      timeout: 30ms
      retries: 3
      test: env | grep $HOME
    env_file:
      - apps/fe/.env
    depends_on:
      - api
    ports:
      - 3000:3000
    networks:
       - app-network
  ### ===================================
  ### API SERVICE TERITORY
  ### ===================================
  api:
    container_name: api
    image: api:latest
    restart: always
    mem_limit: 512m
    mem_swappiness: 70
    command: ./api
    healthcheck:
      interval: 120ms
      start_period: 60ms
      timeout: 30ms
      retries: 3
      test: env | grep $HOME
    env_file:
      - apps/be/.env
    depends_on:
      - db
      - cache
    ports:
      - 4000:4000
    networks:
       - app-network
  # ### ===================================
  # ### WORKER SERVICE TERITORY
  # ### ===================================
  worker:
    container_name: worker
    image: api:latest
    restart: always
    mem_limit: 1gb
    mem_swappiness: 70
    command: ./worker
    healthcheck:
      interval: 120ms
      start_period: 60ms
      timeout: 30ms
      retries: 3
      test: env | grep $HOME
    env_file:
      - apps/be/.env
    depends_on:
      - db
      - cache
    expose:
      - 4000
    networks:
       - app-network
  # ### ===================================
  # ### SCHEDULER SERVICE TERITORY
  # ### ===================================
  scheduler:
    container_name: scheduler
    image: api:latest
    restart: always
    mem_limit: 1gb
    mem_swappiness: 70
    command: ./scheduler
    healthcheck:
      interval: 120ms
      start_period: 60ms
      timeout: 30ms
      retries: 3
      test: env | grep $HOME
    env_file:
      - apps/be/.env
    depends_on:
      - db
      - cache
    expose:
      - 4000
    networks:
       - app-network
  # ### ===================================
  # ### DATABASE SERVICE TERITORY
  # ### ===================================
  db:
    image: postgres:14-alpine
    restart: always
    healthcheck:
      interval: 120ms
      start_period: 60ms
      timeout: 30ms
      retries: 3
      test: env | grep $HOME
    env_file:
      - apps/be/.env
    ports:
      - 5432:5432
    networks:
       - app-network
  # ### ===================================
  # ### CACHING SERVICE TERITORY
  # ### ===================================
  cache:
    image: redis:7-alpine
    restart: always
    healthcheck:
      interval: 120ms
      start_period: 60ms
      timeout: 30ms
      retries: 3
      test: env | grep $HOME
    ports:
      - 6379:6379
    networks:
       - app-network
  # ### ===================================
  # ### SEARCH SERVICE TERITORY
  # ### ===================================
  search:
    image: getmeili/meilisearch:latest
    restart: always
    mem_limit: 1gb
    mem_swappiness: 70
    healthcheck:
      interval: 120ms
      start_period: 60ms
      timeout: 30ms
      retries: 3
      test: env | grep $HOME
    env_file:
      - apps/be/.env
    ports:
      - 7700:7700
    networks:
     - app-network
  ### ===================================
  ### NETWORKS SHARING GROUP TERITORY
  ### ===================================
networks:
  app-network: